# Change these first
owner: FunctionalMetatable # Your GitHub organization or username, where this repository lives
repo: magnifier-api-upptime-test # The name of this repository

sites:
  - name: Magnifier API
    url: https://magnifier-api.potatophant.net
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /magnifier-api-upptime-test
  logoUrl: https://github.com/CluckCluckChicken/Magnifier/raw/main/Spyglass/wwwroot/images/icon.png
  name: Magnifier upptime
  introTitle: "haha lets see how google breaks"
  introMessage: prob unfunny
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Magnifier
      href: https://magnifier.potatophant.net/
  scripts:
    - src: https://functionalmetatable.github.io/js/set-front-bg-magnifier.js

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
